name: Go por Exemplos
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: [ ubuntu-latest ]
    steps:

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.0

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build
        run: |
          tools/build
          cp .github/workflows/README.md ./public
          
      - name: Deploy to goporexemplos
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.ACCESS_TOKEN }}
          external_repository: goporexemplos/goporexemplos.github.io
          publish_branch: master
          publish_dir: ./public
